### ISSUE TITLE
please show me an example 

### ISSUE THREAD

**Issue by Reinhartd** [altelch/SonoffIR#1]
Thanks for the good documentation.
Can you show me an example of the call?

The Samsung Key_Power is "0x40BF", how is the JSON String/Command?

IRsend {"protocol": "SAMSUNG","bits": 32 "data": 1..(2^32)-1}

LG

**Comment by altelch** [comment]
Hi,

0x40BF is hex for the 32bit code you want to transfer. The decimal representation is 16575 so command would be: {"protocol": "SAMSUNG","bits": 32 "data": 16575}

**Comment by Reinhartd** [comment]
Thank you, i will test it!

**Comment by altelch** [comment]
I think you only have the command data and miss the precode. Please check http://lirc.sourceforge.net/remotes/samsung/ for your remote type and check pre_data and pre_data_bits.
This needs to be padded in front of the command data. If you have eg. pre_data 0xFF and pre_data_bits of 26 you need to convert 0xFF40BF to decimal and set bits to 32+26. The pre data depends on your remote type. I only tested wiht LG but there it worked.

**Comment by Reinhartd** [comment]
This is the documentation from lirc.

`name  Samsung_BN59-00940A
bits           16
flags SPACE_ENC|CONST_LENGTH
eps            30
aeps          100
header       4605  4344
one           678  1551
zero          678   436
ptrail        679
pre_data_bits   16
pre_data       0xE0E0
gap          107626
toggle_bit_mask 0x0
KEY_POWER      0x40BF         `

is this correct?
`
bits  16
pre_data_bits   16
pre_data            0xE0E0
Power On/Off   0x40BF
E0E040BF      = 3772793023`

then the Json String is:
` irsend  {"protocol": "SAMSUNG","bits": 32, "data": 3772793023}`

LG

**Comment by altelch** [comment]
Hi, yes, that looks good.

Greetings,
    Heiko.

**Comment by Reinhartd** [comment]
I tested this today on my Samsung curved 55 and everything works perfectly!
Thanks again for your good support!

LG

**Comment by altelch** [comment]
Closed.
