### ISSUE TITLE
How include this implementation to Tasmota

### ISSUE THREAD

**Issue by douglaspaulo** [altelch/SonoffIR#2]
Hi @altelch 

How i include this irsend implementation to my Tasmota firmware?

I don´t found any code that I can insert on my Tasmota to upload for Sonoff Basic.

Can you help me implement this?

Thanks

**Comment by altelch** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration at the Bottom to get the MQTT commands or use the webpage of your sonoff device to configure GPIO Pin 14 as IRsend.
